---
root:
lsi: false

# Site configuration
title:        'Svatba Lucka a Kuba'
description:  'Svatba Lucka a Kuba, 25. 7. 2015 Hrad Strakonice. Svobodu jsme již vyzkoušeli, manželství ještě neznáme, sňatek uzavřít hodláme.'
author:       'Jakub Korál a Lucie Toušková'

# include: ['favicon.png', 'favicon.ico', 'apple-touch-icon-precomposed.png']
exclude: ['*.styl', '*.coffee', 'node_modules']
